using System.ComponentModel.Composition;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuizMaker.Application.Contracts.DTOs.Quiz;
using QuizMaker.Application.Interfaces;

namespace QuizMaker.Exporters.Pdf;

[Export(typeof(IQuizExporter))]
public class PdfExporter : IQuizExporter {
    public string Format { get; set; } = "pdf";
    public string ContentType { get; set; } = "application/pdf";

    public PdfExporter() {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<byte[]> ExportAsync(QuizDetailDto quiz) {
        var document = Document.Create(container => {
            container.Page(page => {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text($"Quiz: {quiz.Name}")
                    .SemiBold().FontSize(24).FontColor(Colors.Blue.Medium);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(column => {
                        column.Spacing(10);

                        if (quiz.Questions != null) {
                            int index = 1;
                            foreach (var q in quiz.Questions) {
                                column.Item().Row(row => {
                                    row.AutoItem().Text($"{index++}. ").Bold();
                                    row.RelativeItem().Column(c => {
                                        c.Item().Text(q.Text).SemiBold();
                                    });
                                });
                            }
                        }
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x => {
                        x.Span("Generated by QuizMaker - Page ");
                        x.CurrentPageNumber();
                    });
            });
        });

        return Task.FromResult(document.GeneratePdf());
    }
}