<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.12.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuizMaker.Application\QuizMaker.Application.csproj" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /Y /S /I &quot;$(TargetDir)*&quot; &quot;$(SolutionDir)QuizMaker.Api\bin\Debug\net8.0\Exporters\&quot;" />
	</Target>
</Project>
